# Generated by Django 4.1.4 on 2023-01-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-timestamp']},
        ),
    ]
