# Generated by Django 4.1.4 on 2023-01-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['timestamp']},
        ),
    ]
