# Generated by Django 4.1.4 on 2023-01-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
    ]
