# Generated by Django 4.1.4 on 2023-01-02 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 16, 51, 19, 226561)),
        ),
    ]
