# Generated by Django 4.1.4 on 2023-01-25 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_device_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereg',
            name='last_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devicereg',
            name='status',
            field=models.CharField(default='Deactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 10, 31, 29, 788752)),
        ),
    ]
