# Generated by Django 4.1.4 on 2023-01-25 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_device_timestamp_alter_devicereg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereg',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='devicereg',
            name='status',
        ),
        migrations.AlterField(
            model_name='device',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 12, 52, 4, 374038)),
        ),
        migrations.CreateModel(
            name='TempDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 1, 25, 12, 52, 4, 375038))),
                ('device_id', models.CharField(max_length=255)),
                ('energy_consumption', models.IntegerField(default=0)),
                ('device_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicereg')),
                ('is_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.deviceconnection')),
            ],
            options={
                'db_table': 'temp_device_data',
            },
        ),
    ]
