# Generated by Django 4.1.4 on 2023-01-25 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_remove_devicereg_last_time_remove_devicereg_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereg',
            name='sensor_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 17, 13, 11, 758011)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 17, 13, 11, 759012)),
        ),
    ]
