# Generated by Django 4.1.4 on 2023-01-30 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_devicereg_sensor_id_alter_device_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tempdevice',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 10, 32, 6, 564711)),
        ),
        migrations.AddField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 10, 32, 6, 565710)),
        ),
    ]
