# Generated by Django 4.1.4 on 2023-01-30 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_remove_device_timestamp_remove_tempdevice_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereg',
            name='status',
            field=models.CharField(default='Disconnected', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 10, 48, 52, 32566)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 10, 48, 52, 32566)),
        ),
    ]
