# Generated by Django 4.1.4 on 2023-02-01 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_devicereg_status_alter_device_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereg',
            name='today_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicereg',
            name='yesterday_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 37, 37, 277372)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 10, 37, 37, 278372)),
        ),
    ]
