# Generated by Django 4.1.4 on 2023-03-01 04:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_devicereg_today_total_devicereg_yesterday_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data_type',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='is_powered',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='total_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tempdevice',
            name='data_type',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tempdevice',
            name='is_powered',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='tempdevice',
            name='total_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 10, 26, 47, 182034)),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_connected',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.deviceconnection'),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 10, 26, 47, 182034)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='is_connected',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.deviceconnection'),
        ),
    ]
