# Generated by Django 4.1.4 on 2023-03-01 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_device_data_type_device_is_powered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdevice',
            name='data_type',
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 11, 6, 7, 446126)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 11, 6, 7, 446126)),
        ),
    ]
