# Generated by Django 4.1.4 on 2023-03-01 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_alter_device_created_at_alter_tempdevice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 3, 5, 885999)),
        ),
        migrations.AlterField(
            model_name='device',
            name='data_type',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 3, 5, 886999)),
        ),
    ]
