# Generated by Django 4.1.4 on 2023-03-01 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_alter_device_created_at_alter_device_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 18, 8, 50, 136210)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 18, 8, 50, 137210)),
        ),
    ]
