# Generated by Django 4.1.4 on 2023-03-14 03:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_alter_device_created_at_alter_tempdevice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 9, 42, 54, 406606)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 9, 42, 54, 406606)),
        ),
        migrations.CreateModel(
            name='ActualDeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 14, 9, 42, 54, 406606))),
                ('device_id', models.CharField(max_length=255)),
                ('energy_consumption', models.IntegerField(default=0)),
                ('is_powered', models.BooleanField(default=1)),
                ('data_type', models.BooleanField(default=1)),
                ('total_consumption', models.FloatField(default=0.0)),
                ('device_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicereg')),
                ('is_connected', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.deviceconnection')),
            ],
            options={
                'db_table': 'actual_device_data',
            },
        ),
    ]
