# Generated by Django 4.1.4 on 2023-03-15 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_alter_device_created_at_alter_tempdevice_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualdevicedata',
            name='device_connectivity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_connectivity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tempdevice',
            name='device_connectivity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actualdevicedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 15, 3, 21, 436093)),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 15, 3, 21, 435093)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 15, 3, 21, 435093)),
        ),
    ]
