# Generated by Django 4.1.4 on 2023-03-15 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_actualdevicedata_device_connectivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualdevicedata',
            name='device_connectivity',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_connectivity',
        ),
        migrations.RemoveField(
            model_name='tempdevice',
            name='device_connectivity',
        ),
        migrations.AlterField(
            model_name='actualdevicedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 18, 10, 42, 807978)),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 18, 10, 42, 806979)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 18, 10, 42, 807978)),
        ),
    ]
