# Generated by Django 4.1.4 on 2023-03-16 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_remove_actualdevicedata_device_connectivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualdevicedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 50, 44, 765316)),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 50, 44, 764316)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 50, 44, 764316)),
        ),
        migrations.CreateModel(
            name='SummaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date(2023, 3, 16))),
                ('device_id', models.CharField(max_length=255)),
                ('total_consumption', models.FloatField(default=0.0)),
                ('device_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicereg')),
            ],
        ),
    ]
