# Generated by Django 4.1.4 on 2023-03-16 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_alter_actualdevicedata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualdevicedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 51, 45, 317174)),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 51, 45, 316173)),
        ),
        migrations.AlterField(
            model_name='tempdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 51, 45, 317174)),
        ),
        migrations.AlterModelTable(
            name='summarydata',
            table='summary_data',
        ),
    ]
